-- 테이블 생성
CREATE TABLE FOOD (
    FNAME VARCHAR2(100),
    PRICE NUMBER
);

-- 데이터 추가 : INSERT
INSERT INTO FOOD(FNAME, PRICE) VALUES ('호두마루', 1000);
INSERT INTO FOOD(FNAME, PRICE) VALUES ('체리마루', 1000);
INSERT INTO FOOD(FNAME, PRICE) VALUES ('녹차마루', 1000);

-- 데이터 조회 : SELECT
SELECT FNAME, PRICE FROM FOOD;

-- 데이터 삭제 : DELETE
DELETE FROM FOOD WHERE FNAME = '녹차마루';

-- 데이터 수정 : UPDATE

-- 테이블 삭제
DROP TABLE FOOD;