DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO                  NUMBER                  PRIMARY KEY
    , ID                VARCHAR2(100)           NOT NULL UNIQUE
    , PWD               VARCHAR2(100)           NOT NULL
    , JOIN_DATE         TIMESTAMP               DEFAULT SYSDATE
    , DEL_YN            CHAR(1)                 DEFAULT 'N' CHECK(DEL_YN IN('Y','N'))
);

--  DEFAULT 'N' CHECK(DEL_YN IN('Y','n')) -> 소문자 땜시 안됐었음
----------------------

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , JOIN_DATE     TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN('Y','N') )
);

SELECT * FROM MEMBER;