DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO                  NUMBER                  PRIMARY KEY
    , ID                VARCHAR2(100)           NOT NULL UNIQUE
    , PWD               VARCHAR2(100)           NOT NULL
    , JOIN_DATE         TIMESTAMP               DEFAULT SYSDATE
    , DEL_YN            CHAR(1)                 DEFAULT 'N' CHECK(DEL_YN IN('Y','N'))
);

--  DEFAULT 'N' CHECK(DEL_YN IN('Y','n')) -> 소문자 땜시 안됐었음
----------------------

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , JOIN_DATE     TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN('Y','N') )
);

SELECT * FROM MEMBER;



DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCACHE NOCYCLE;
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL UNIQUE
    , CONTENT       VARCHAR2(4000)   NOT NULL
    , INSERT_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN('Y','N') )
);

SELECT * FROM BOARD;
COMMIT;





--// insert
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD.NEXTVAL, 'ABC', 'ASDFASDAFF');

--// update
UPDATE BOARD SET CONTENT = 'zzzz' WHERE NO = 1;

--// delete
UPDATE BOARD SET DEL_YN = 'Y' WHERE NO = '1';

--// selectList
SELECT * FROM BOARD WHERE DEL_YN = 'N' ORDER BY NO DESC;
-- 퀴리실행하는게 웹사이트 사용..? DB 조작

--// selectOne
SELECT * FROM BOARD WHERE NO = 1 AND DEL_YN = 'N';
SELECT * FROM BOARD WHERE NO = ? AND DEL_YN = 'N';











----------------------------------

DROP SEQUENCE SEQ_BOOK;
CREATE SEQUENCE SEQ_BOOK NOCACHE NOCYCLE;
DROP TABLE BOOK CASCADE CONSTRAINTS;
CREATE TABLE BOOK(
    NO                  NUMBER          PRIMARY KEY
    , TITLE             VARCHAR2(100)   NOT NULL
    , AUTHOR            VARCHAR2(100)
    , PRICE             NUMBER          NOT NULL
    , PUBLISHED_DATE    TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN            CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN ('Y','N') )
);



--도서 등록
INSERT INTO BOOK(NO, TITLE, AUTHOR, PRICE) VALUES(SEQ_BOOK.NEXTVAL , '해리포터' , '허균' , 3000);
--도서 가격 수정 (번호 , 가격)
UPDATE BOOK SET PRICE = 500 WHERE NO = 1;
--도서 삭제 (번호)
UPDATE BOOK SET DEL_YN = 'Y' WHERE NO = 1;
--도서 목록 조회 (번호, 제목)
SELECT * FROM BOOK WHERE DEL_YN = 'N' ORDER BY NO DESC;
--도서 상세 조회 (모든 칼럼)
SELECT * FROM BOOK WHERE NO = 1 AND DEL_YN = 'N';


