DROP SEQUENCE SEQ_JELLIES;
CREATE SEQUENCE SEQ_JELLIES NOCACHE NOCYCLE;

DROP TABLE JELLIES CASCADE CONSTRAINTS;
CREATE TABLE JELLIES(
    NO                  NUMBER              PRIMARY KEY
    , FLAVOR            VARCHAR2(300)       NOT NULL
    , PRICE             NUMBER              NOT NULL
    , MFG               TIMESTAMP           DEFAULT SYSDATE
    , DEL_YN            CHAR(1)             DEFAULT 'N' CHECK ( DEL_YN IN ('Y', 'N'))
);

SELECT * FROM JELLIES;
COMMIT;

-- insert
INSERT INTO JELLIES(NO, FLAVOR, PRICE) VALUES(SEQ_JELLIES.NEXTVAL, '딸기맛', '500');
-- update
UPDATE JELLIES SET PRICE = 450 WHERE NO = 1;
-- delete
UPDATE JELLIES SET DEL_YN = 'Y' WHERE NO = 1;
-- selectList
SELECT * FROM JELLIES WHERE DEL_YN = 'N' ORDER BY NO DESC;
-- listOne
SELECT * FROM JELLIES WHERE NO = 1 AND DEL_YN = 'N';