CREATE TABLE STUDENT (
    NAME VARCHAR2(100)
);

TRUNCATE TABLE STUDENT;


SELECT *
FROM STUDENT;

DROP TABLE BOOK CASCADE CONSTRAINTS;
CREATE TABLE BOOK (
    TITLE   VARCHAR2(100)
    , AUTHOR VARCHAR2(100)
    , PRICE NUMBER
--    , PUBLISHED_DATE    
);

SELECT *
FROM BOOK;

DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCACHE NOCYCLE;

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    NO                  NUMBER              PRIMARY KEY
    , TITLE             VARCHAR2(100)       NOT NULL
    , CONTENT           VARCHAR2(100)       NOT NULL
    , CREATED_DATE      TIMESTAMP           DEFAULT SYSDATE
);

SELECT * FROM BOARD;

-- 게시글 작성
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD.NEXTVAL, ?,?);

-- 게시글 목록 조회
SELECT * FROM BOARD;