-- 테이블 생성
CREATE TABLE BOOK(
    TITLE VARCHAR2(100),
    PRICE NUMBER
);

-- 데이터 추가 : INSERT
INSERT INTO BOOK(TITLE, PRICE) VALUES ('해리포터1', 1000);
INSERT INTO BOOK(TITLE, PRICE) VALUES ('해리포터2', 2000);
INSERT INTO BOOK(TITLE, PRICE) VALUES ('해리포터3', 3000);
-- 데이터 조회 : SELECT
SELECT TITLE, PRICE FROM BOOK;
-- 데이터 삭제 : DELETE
DELETE FROM BOOK WHERE TITLE = '해리포터2';
-- 데이터 수정 : UPDATE

-- 테이블 삭제
DROP TABLE BOOK;