DROP TABLE BORAD;

INSERT INTO BORAD(TITLE, CONTENT) VALUES('나는', '심원용')
COMMIT;


SELECT *
FROM BORAD;

UPDATE BORAD
    SET
        TITLE = 'ㅋㅋㅋ'
        WHERE CONTENT = '심원용'
COMMIT;

DELETE BORAD WHERE CONTENT = '심원용'
